repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        args: [--line-length=160]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        additional_dependencies: [flake8==6.1.0]
        types: [python]
        args:
          - "--max-line-length=160"
          - "--extend-ignore=F401,E203,W291,W293"
          - "--exclude=archive"
        exclude: '^archive/'
