# render.yaml - Render.com Blueprint Configuration
services:
  # Main Web Application
  - type: web
    name: postopus-web
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.web.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    healthCheckPath: "/health"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: DATABASE_URL
        fromDatabase:
          name: postopus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: postopus-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: VK_API_VERSION
        value: "5.131"
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"

  # PostgreSQL Database
  - type: pserv
    name: postopus-db
    env: postgresql
    plan: starter
    databases:
      - name: postopus
        user: postopus_user

  # Redis for Celery/Caching
  - type: redis
    name: postopus-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

  # Background Worker (Celery)
  - type: worker
    name: postopus-worker
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A src.tasks.celery_app worker --loglevel=info"
    envVars:
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: DATABASE_URL
        fromDatabase:
          name: postopus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: postopus-redis
          property: connectionString
      - key: ENVIRONMENT
        value: "production"